# Generated by Django 5.0.1 on 2024-08-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreverfinds', '0006_remove_product_user_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
